openapi: 3.0.3
info:
  title: Simple Enum Test API
  version: 1.0.0

paths:
  /user/{userId}/marital-status:
    get:
      summary: Get user marital status
      operationId: getMaritalStatus
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                example: "MARRIED"

components:
  schemas:
    MaritalStatus:
      type: string
      enum:
        - "Женат / За мужем"
        - "Холост / Не замужем"
        - "Разведен(а)"
        - "Вдовец / Вдова"
      x-enum-varnames:
        - "MARRIED"
        - "SINGLE"
        - "DIVORCED"
        - "WIDOWED"


    WeatherType:
      type: integer
      format: int32
      enum:
        - 42
        - 18
        - 56
      x-enum-descriptions:
        - 'Blue sky'
        - 'Slightly overcast'
        - 'Take an umbrella with you'
      x-enum-varnames:
        - Sunny
        - Cloudy
        - Rainy
