openapi: 3.0.0
info:
  title: Simple Enum Test API
  version: 1.0.0

paths:
  /user/{userId}/marital-status:
    get:
      summary: Get user marital status
      operationId: getMaritalStatus
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                example: "MARRIED"

components:
  schemas:
    MaritalStatus:
      type: string
      enum:
        - MARRIED
        - SINGLE
        - DIVORCED
        - WIDOWED
      x-enum-labels:
        MARRIED: "Женат / За мужем"
        SINGLE: "Холост / Не замужем"
        DIVORCED: "Разведен(а)"
        WIDOWED: "Вдовец / Вдова"